[versions]
activityCompose = "1.12.3"
androidGradlePlugin = "9.0.0"
androidxCamera = "1.5.3"
androidxCoreKtx = "1.17.0"
androidxCoreSplashscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxLifecycle = "2.10.0"
androidxMedia3 = "1.9.2"
androidxNavigation3 = "1.0.0"
androidxPaging3 = "3.4.0"
androidxRoom = "2.8.4"
androidxWork = "2.11.1"
coil = "3.3.0"
composeBom = "2026.01.01"
googleAccompanist = "0.37.3"
googleMlkit = "17.3.0"
googleServicesLocation = "21.3.0"
koin = "4.1.1"
koinAnnotations = "2.3.1"
komm = "0.25.0"
kotlin = "2.3.10"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.10.0"
kotlinxCoroutines = "1.10.2"
ksp = "2.3.5"
ktor = "3.4.0"
konform = "0.11.1"
okio = "3.16.4"
orbit = "11.0.0"

compileSdk = "36"
targetSdk = "36"
minSdk = "26"
java = "17"

[libraries]
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamera" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidxCamera" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-lifecycle-viewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidxLifecycle" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }

androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }

androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "androidxMedia3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidxMedia3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidxMedia3" }
androidx-media3-ui-compose-material3 = { group = "androidx.media3", name = "media3-ui-compose-material3", version.ref = "androidxMedia3" }

androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidxNavigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidxNavigation3" }

androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidxPaging3" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging3" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidxRoom" }

androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }

coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
coil = { group = "io.coil-kt.coil3", name = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
coil-compose-core = { group = "io.coil-kt.coil3", name = "coil-compose-core" }
coil-network-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
coil-video = { group = "io.coil-kt.coil3", name = "coil-video" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }

com-google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "googleAccompanist" }
com-google-mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "googleMlkit" }
com-google-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "googleServicesLocation" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup", version.ref = "koin" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koinAnnotations" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koinAnnotations" }

komm-annotations = { group = "com.ucasoft.komm", name = "komm-annotations", version.ref = "komm" }
komm-processor = { group = "com.ucasoft.komm", name = "komm-processor", version.ref = "komm" }
komm-plugins-enum = { group = "com.ucasoft.komm", name = "komm-plugins-enum", version.ref = "komm" }

ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

konform-jvm = { group = "io.konform", name = "konform-jvm", version.ref = "konform" }

okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }
orbit-test = { group = "org.orbit-mvi", name = "orbit-test", version.ref = "orbit" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidxRoom" }

convention-platform = { group = "kz.rymbek.platform.common.base.convention", name = "convention-platform" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidxRoom" }

# Plugins defined by this project
# Application
convention-application = { id = "convention.application" }
convention-application-compose = { id = "convention.application.compose" }
convention-library = { id = "convention.library" }
convention-library-compose = { id = "convention.library.compose" }
convention-jvm = { id = "convention.jvm" }

# Dependency
dependency-koin = { id = "dependency.koin" }
dependency-room = { id = "dependency.room" }
dependency-serialization = { id = "dependency.serialization" }

# Module Platform
module-platform-converter = { id = "module.platform.converter" }
module-platform-database = { id = "module.platform.database" }
module-platform-data = { id = "module.platform.data" }
module-platform-datastore = { id = "module.platform.datastore" }
module-platform-domain = { id = "module.platform.domain" }
module-platform-feature = { id = "module.platform.feature" }
module-platform-model-base = { id = "module.platform.model.base" }
module-platform-model-cache = { id = "module.platform.model.cache" }
module-platform-model-remote = { id = "module.platform.model.remote" }
module-platform-model-ui = { id = "module.platform.model.ui" }
module-platform-network = { id = "module.platform.network" }
module-platform-work = { id = "module.platform.work" }
